---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helloservice
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./delivery/manifest
  prune: true
  sourceRef:
    kind: GitRepository
    name: helloservice
  validation: client

